---
fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib'
      ref: '4.12.0'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat'
  symlinks:
    'eosserver': "#{source_dir}"
