---
fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat'
    yumrepo_core:
      repo: "git://github.com/puppetlabs/puppetlabs-yumrepo_core"
      puppet_version: ">= 6.0.0"
  symlinks:
    'eosserver': "#{source_dir}"
